### ISSUE TITLE
mpd2sc: sigcatcher does nothing

### ISSUE THREAD

**Issue by joerg-krause** [medoc92/sc2mpd#15]
Using CTRL^C does not exit the process, but only logs.

**Comment by joerg-krause** [comment]
Just figured it is only true if mpd2sc is used without the `-p` option.

**Comment by medoc92** [comment]
I added a bit of code which should hopefully improve the situation. But this never seemed to be a problem in practise, how did you detect the issue ?

**Comment by joerg-krause** [comment]
Thanks! This works. I've started mpd2sc on the command line and tried to exit it with CTRL^C.
