### ISSUE TITLE
build error with latest commit

### ISSUE THREAD

**Issue by espakman** [medoc92/sc2mpd#18]
I just tried to build the latest sc2mpd and getting the following build error (raspberrypi 3, archlinux):

building ohSongcast
mkdir -p Build/Obj/Posix/Release/
g++ -fPIC -o Build/Obj/Posix/Release/Ohm.o -c -fexceptions -Wall -Werror -pipe -std=c++11 -D_GNU_SOURCE -D_REENTRANT -DDEFINE_LITTLE_ENDIAN -DDEFINE_TRACE -O2 -fvisibi lity=hidden -DDllImport="__attribute__ ((visibility(\"default\")))" -DDllExport="__attribute__ ((visibility(\"default\")))" -DDllExportClass="__attribute__ ((visibilit y(\"default\")))" -Wno-psabi -I../ohNet/Build/Include/ -I../ohNetGenerated/Build/Include/ -I../ohTopology/build/Include/  Ohm.cpp
g++ -fPIC -o Build/Obj/Posix/Release/OhmMsg.o -c -fexceptions -Wall -Werror -pipe -std=c++11 -D_GNU_SOURCE -D_REENTRANT -DDEFINE_LITTLE_ENDIAN -DDEFINE_TRACE -O2 -fvis ibility=hidden -DDllImport="__attribute__ ((visibility(\"default\")))" -DDllExport="__attribute__ ((visibility(\"default\")))" -DDllExportClass="__attribute__ ((visibi lity(\"default\")))" -Wno-psabi -I../ohNet/Build/Include/ -I../ohNetGenerated/Build/Include/ -I../ohTopology/build/Include/  OhmMsg.cpp
g++ -fPIC -o Build/Obj/Posix/Release/OhmSocket.o -c -fexceptions -Wall -Werror -pipe -std=c++11 -D_GNU_SOURCE -D_REENTRANT -DDEFINE_LITTLE_ENDIAN -DDEFINE_TRACE -O2 -f visibility=hidden -DDllImport="__attribute__ ((visibility(\"default\")))" -DDllExport="__attribute__ ((visibility(\"default\")))" -DDllExportClass="__attribute__ ((vis ibility(\"default\")))" -Wno-psabi -I../ohNet/Build/Include/ -I../ohNetGenerated/Build/Include/ -I../ohTopology/build/Include/  OhmSocket.cpp
g++ -fPIC -o Build/Obj/Posix/Release/OhmReceiver.o -c -fexceptions -Wall -Werror -pipe -std=c++11 -D_GNU_SOURCE -D_REENTRANT -DDEFINE_LITTLE_ENDIAN -DDEFINE_TRACE -O2  -fvisibility=hidden -DDllImport="__attribute__ ((visibility(\"default\")))" -DDllExport="__attribute__ ((visibility(\"default\")))" -DDllExportClass="__attribute__ ((v isibility(\"default\")))" -Wno-psabi -I../ohNet/Build/Include/ -I../ohNetGenerated/Build/Include/ -I../ohTopology/build/Include/  OhmReceiver.cpp
g++ -fPIC -o Build/Obj/Posix/Release/OhmProtocolMulticast.o -c -fexceptions -Wall -Werror -pipe -std=c++11 -D_GNU_SOURCE -D_REENTRANT -DDEFINE_LITTLE_ENDIAN -DDEFINE_T RACE -O2 -fvisibility=hidden -DDllImport="__attribute__ ((visibility(\"default\")))" -DDllExport="__attribute__ ((visibility(\"default\")))" -DDllExportClass="__attrib ute__ ((visibility(\"default\")))" -Wno-psabi -I../ohNet/Build/Include/ -I../ohNetGenerated/Build/Include/ -I../ohTopology/build/Include/  OhmProtocolMulticast.cpp
g++ -fPIC -o Build/Obj/Posix/Release/OhmProtocolUnicast.o -c -fexceptions -Wall -Werror -pipe -std=c++11 -D_GNU_SOURCE -D_REENTRANT -DDEFINE_LITTLE_ENDIAN -DDEFINE_TRA CE -O2 -fvisibility=hidden -DDllImport="__attribute__ ((visibility(\"default\")))" -DDllExport="__attribute__ ((visibility(\"default\")))" -DDllExportClass="__attribut e__ ((visibility(\"default\")))" -Wno-psabi -I../ohNet/Build/Include/ -I../ohNetGenerated/Build/Include/ -I../ohTopology/build/Include/  OhmProtocolUnicast.cpp
make: *** No rule to make target '../ohNetGenerated/Build/Obj/Posix/Release/DvAvOpenhomeOrgReceiver1.o', needed by 'Build/Obj/Posix/Release/Receiver.elf'.  Stop.
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by medoc92** [comment]
what does gcc -dumpmachine report on your system ?

**Comment by espakman** [comment]
# gcc -dumpmachine
armv7l-unknown-linux-gnueabihf

Regards,
Eric

**Comment by medoc92** [comment]
How did you invoke ohbuild.sh ?

**Comment by espakman** [comment]
From within an Archlinux PKGBUILD file:

  sh ./ohbuild.sh -b openhome
  ./autogen.sh
  ./configure --prefix=/usr --with-openhome=openhome
  make

**Comment by medoc92** [comment]
I have trouble reproducing this (on x64, so this may be an architecture issue). 

I should have asked already: what do you mean by latest sc2mpd ? The github code or a tar file ?

**Comment by espakman** [comment]
The github code, after commit: 600e7d6c4d20cf16f6064c7923a3e6ee9d2f678a

**Comment by medoc92** [comment]
Ok, same for me. Last thing before I have to install arch on a Pi: are you doing this in an initially empty directory (I guess yes...)

**Comment by espakman** [comment]
Yes correct, the previous snippet missed a part:
  mkdir openhome
  sh ./ohbuild.sh -b openhome

**Comment by medoc92** [comment]
I think that this should be fixed by the commit from tonight.

**Comment by espakman** [comment]
Thanks! I'm not at home today but will try tomorrow and report

**Comment by espakman** [comment]
the issue is fixed now. Thanks
