### ISSUE TITLE
Building a Debian package from Git

### ISSUE THREAD

**Issue by TripleEmcoder** [medoc92/sc2mpd#4]
Can you post instructions for building a Debian package directly from the sc2mpd repository, to test out latest commits? In particular I would like to test sccvttype NONE.

What commands do I need to run after git clone? I have tried various combinations of gbp buildpackage, but that only got me so far as to produce broken packages without any content other than docs.

**Comment by TripleEmcoder** [comment]
So in a classic case of rubber duck problem solving, I managed to figure it out shortly after posting. I'm not sure this is the true Debian way of doing building, but this got me a correct package:

`
git close (...)
autogen.sh
ohbuild.sh openhome
configure --with-openhome=openhome
debuild -B -us -uc
`

I suppose all this should be possible to run automatically with gbp or some other Debian magic, but I'm way over my head here.

**Comment by medoc92** [comment]
Ok, I see you figured it out. I was answering you through email, but you actually taught me something here, I'll have to try it :) I always go through a tar dist when building packages.

Otherwise, the "classical" build instructions are on the following link (end of the page), but I guess you saw them:
http://www.lesbonscomptes.com/upmpdcli/sc2mpd.html

**Comment by TripleEmcoder** [comment]
So when you go through a dist tar, how do you do that? I imagine first generate a tarball and then build it effectively the same way as apt-get source -b?

Sure, I know the classical build trio of configure/make/make install, but Debian packaging is something totally new. Maybe I overcomplicated things, but since I already had the sc2mpd package installed, overwriting it with my own seemed the logical thing to do.

**Comment by medoc92** [comment]
I'd need to write up the details while I do it, but the general idea is to copy the tar file to an empty directory, rename it (pkgname-a.b.c.tar.gz -> pkgname_a.b.c.orig.tar.gz), extract it, copy the debian directory into the extracted tree, and run debuild in there.

The version must be adjusted in the changelog file to match the one in the tar file name.

**Comment by medoc92** [comment]
I added a section about how I build the debs from the released tarfiles at the end of this page:
http://www.lesbonscomptes.com/upmpdcli/sc2mpd.html
