### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by joerg-krause** [medoc92/sc2mpd#8]
I am about to integrate sc2mpd (and the OpenHome stack) into [Buildroot](https://buildroot.org), when I noticed that sc2mpd is not having a license yet.

**Comment by joerg-krause** [comment]
Fixed by bdea740027b075e0d1fa250aa3d1780dee70aa53. Thanks!

**Comment by medoc92** [comment]
Ooops, I'm not sure of what I did. Looking at the code, there are pieces which come from OpenHome, which is under a 2-clause BSD License. I don't think that there is an actual problem, but I don't know either how the whole package should be licensed. Any idea ?

**Comment by medoc92** [comment]
After reading about this, I think that this can be GPL, no problem, but the BsdLicense.txt file should be packaged (which I don't do currently, I'll fix it).

**Comment by joerg-krause** [comment]
I think so, too. Note, that some packages do used the MIT license (ohnet), which should be packaged, too.

**Comment by medoc92** [comment]
The Mit License is for the current code. The frozen version which ohbuild.sh extracts (or which is in the distributed tar file) was under BSD. I'll update it one day, but the openhome code is not always quite stable, and this version works for what we do as far as I could see...

**Comment by joerg-krause** [comment]
I see!
